### ISSUE TITLE
live_view error

### ISSUE THREAD

**Issue by gwlee5482** [Jiloc/edsdk-python#5]
Using the example of "seve_image.py", we tried to implement live_view by adding the code at the bottom while leaving the camera call and the session open, but the stream invalid EdsObject 0x000001D3DD765DE0 error occurs in the edsdk.CreateEvfImageRef(stream).

print(edsdk.GetPropertyData(cam, PropID.Evf_OutputDevice,0))
edsdk.SetPropertyData(cam, PropID.Evf_OutputDevice, 0, EvfOutputDevice.PC | EvfOutputDevice.TFT)
stream = edsdk.CreateMemoryStream(0),
evfimage = edsdk.CreateEvfImageRef(stream)
edsdk.DownloadEvfImage(cam, evfimage)

I think the memory is allocated to the stream and I put the image in the memory allocated from CreateEvfImageRef(), did anyone implement live?

**Comment by gwlee5482** [comment]
Do you know how to import images in memory from Python?

**Comment by suatberkantgulen** [comment]
I'm getting this error for live stream:

status = edsdk.DownloadEvfImage(cam, evfimage)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
edsdk.EdsError: EDS_ERR_OBJECT_NOTREADY. Image data set not ready for live view
